
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bxvdvwjmybeixtarqwig.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJ4dmR2d2pteWJlaXh0YXJxd2lnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzY2MDQzMzgsImV4cCI6MjA1MjE4MDMzOH0.FauF-c4D_HtIY5w4UkQVM__iMEAskylY27oSVMYeKQY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  db: {
    schema: 'public'
  },
  auth: {
    persistSession: false, // Don't persist auth state for landing pages
    autoRefreshToken: false,
    detectSessionInUrl: false
  }
});
